[project]
name = "mcp-data-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[duckdb]>=1.10.0",
    "duckdb>=1.2.2",
]
